<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-RN9H6QU" failures="0" tests="6" name="com.api.auto.testcase2.TC_API_CreateWork2" time="0.007" errors="1" timestamp="2023-07-07T14:42:07 ICT" skipped="5">
  <testcase classname="com.api.auto.testcase2.TC_API_CreateWork2" name="TC01_Validate201Created" time="0.000">
    <skipped/>
  </testcase> <!-- TC01_Validate201Created -->
  <system-out/>
  <testcase classname="com.api.auto.testcase2.TC_API_CreateWork2" name="init" time="0.007">
    <error message="Cannot invoke &quot;io.restassured.path.json.JsonPath.getString(String)&quot; because &quot;com.api.auto.testcase2.TC_API_CreateWork2.jsonBody&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "io.restassured.path.json.JsonPath.getString(String)" because "com.api.auto.testcase2.TC_API_CreateWork2.jsonBody" is null
at com.api.auto.testcase2.TC_API_CreateWork2.init(TC_API_CreateWork2.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- init -->
  <system-out/>
  <testcase classname="com.api.auto.testcase2.TC_API_CreateWork2" name="TC02_ValidateWorkId" time="0.000">
    <skipped/>
  </testcase> <!-- TC02_ValidateWorkId -->
  <system-out/>
  <testcase classname="com.api.auto.testcase2.TC_API_CreateWork2" name="TC03_ValidateNameOfWorkMatched" time="0.000">
    <skipped/>
  </testcase> <!-- TC03_ValidateNameOfWorkMatched -->
  <system-out/>
  <testcase classname="com.api.auto.testcase2.TC_API_CreateWork2" name="TC04_ValidateExperienceMatched" time="0.000">
    <skipped/>
  </testcase> <!-- TC04_ValidateExperienceMatched -->
  <system-out/>
  <testcase classname="com.api.auto.testcase2.TC_API_CreateWork2" name="TC05_ValidateEducationMatched" time="0.000">
    <skipped/>
  </testcase> <!-- TC05_ValidateEducationMatched -->
  <system-out/>
</testsuite> <!-- com.api.auto.testcase2.TC_API_CreateWork2 -->
